spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:oracle:thin:@//orahom-scan:1521/csdbhom
    username: VICTORSOUSA
    password: vict201909#
    driverClassName: oracle.jdbc.OracleDriver
server:
  port: 8080


